name: build
run-name: Build Golang application
on:
  push:
    tags:
      - "*.*.*"
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.20.4
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.4"
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: |
          go get .
      - name: Build Linux X86
        run: go build -v -o prime-cache
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Prime Cache - Version ${{ github.ref_name }}
          body: Release version ${{ github.ref_name }} of Prime Cache
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            prime-cache
