name: build
run-name: Build Golang application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.20.4
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.4"
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: |
          go get .
      - name: Build
        run: go build -v ./...
