name: build
run-name: Build Golang application
on:
  push:
    tags:
      - "*.*.*"
permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [linux, windows, darwin, freebsd, openbsd]
        arch: [amd64]
        include:
          - os: linux
            arch: 386
          - os: linux
            arch: arm
          - os: linux
            arch: arm64

          - os: darwin
            arch: arm
          - os: darwin
            arch: arm64

          - os: windows
            arch: amd64
          - os: windows
            arch: 386

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.20.4
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.4"
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: |
          go get .
      - name: Build Linux X86
        run: env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v -o prime-cache
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Prime Cache - Version ${{ github.ref_name }}
          body: Release version ${{ github.ref_name }} of Prime Cache
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            prime-cache
