name: test
run-name: Test and Lint code
on:
  push:

permissions:
  contents: write

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get dependencies
        run: go install .
      - name: Run tests
        run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.1
